models/User.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\web\IdentityInterface;
use \podtserkovsky\userdblog\behaviors\UserDbLogBehavior;

class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_IN_ACTIVE = 0;
    const STATUS_ACTIVE = 1;
    const DEFAULT_PASSWORD = 'Tanesco123';
    public $first_name;
    public $last_name;
    public $role;

    public static function tableName()
    {
        return 'user';
    }

    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'first_name' => Yii::t('app', 'First Name'),
            'last_name' => Yii::t('app', 'Last Name'),
            'username' => Yii::t('app', 'Username'),
            'password' => Yii::t('app', 'Password'),
            'email' => Yii::t('app', 'Email'),
            'auth_key' => Yii::t('app', 'AuthKey'),
            'password_reset_token' => Yii::t('app', 'PasswordResetToken'),
            'access_token' => Yii::t('app', 'AccessToken'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'CreatedAt'),
            'updated_at' => Yii::t('app', 'UpdatedAt'),
            'designation' => Yii::t('app', 'Designation'),
            'coyno' => Yii::t('app', 'Coy No'),
            'created_by' => Yii::t('app', 'Created By'),
            'zone_id' => Yii::t('app', 'Zone'),
            'region_id' => Yii::t('app', 'Region'),
            'district_id' => Yii::t('app', 'District'),
            'role' => Yii::t('app', 'User Role'),
        ];
    }

    public function rules()
    {
        return [
            [['first_name', 'last_name', 'username', 'status', 'zone_id', 'region_id', 'email', 'coyno', 'designation', 'role'], 'required'],
            [['status', 'region_id', 'district_id', 'created_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['username', 'email', 'designation'], 'string', 'max' => 64],
            [['auth_key'], 'string', 'max' => 32],
            [['coyno'], 'string', 'max' => 8],
            [['first_name'], 'string', 'max' => 64],
            [['last_name'], 'string', 'max' => 64],
            [['password_reset_token', 'access_token', 'password'], 'string', 'max' => 255],
            ['username', 'unique', 'targetClass' => '\app\models\User', 'message' => 'This username has already been taken.'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_IN_ACTIVE]],
            [
                ['id'], 'exist', 'skipOnError' => true,
                'targetClass' => AuthAssignment::className(),
                'targetAttribute' => ['id' => 'user_id']
            ],
        ];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->created_at = strtotime('now');
                $this->updated_at = strtotime('now');
                $this->auth_key = Yii::$app->security->generateRandomString();
                $this->access_token = Yii::$app->security->generateRandomString() . ':' . time();
                $this->password = $this->setPassword(self::DEFAULT_PASSWORD);
                $this->created_by = Yii::$app->user->id;
                $this->email = $this->username . '@tanesco.co.tz';
                $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
            }
            return true;
        }
        return false;
    }

    public function afterSave($insert, $changedAttributes)
    {
        $exists = AuthAssignment::find()->where(['=', 'user_id', $this->id])->one();
        $uRole = ($exists) ?: new AuthAssignment();
        $uRole->user_id = $this->id;
        $uRole->item_name = $this->role;
        $uRole->save(false);
        return true;
    }

    /**
     * {@inheritdoc}
     * @return userRole from \app\models\AuthAssignment()
     */
    public static function getRole($role = null)
    {
        $role = ($role != null) ? $role : Yii::$app->user->getId();
        $user_role = AuthAssignment::find()->orderBy('item_name')->where(
            ['=', 'user_id', $role]
        )->one();
        return $user_role['item_name'];
    }

    /**
     * {@inheritdoc}
     * @return userRoles from \app\models\AuthAssignment()
     */
    public function getRoles()
    {
        return $this->hasOne(AuthAssignment::className(), ['user_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     * @return userRoles from \app\models\AuthAssignment()
     */
    public static function getRoleItems()
    {
        return ArrayHelper::map(
            AuthItem::find()->select(['name', 'name'])
                ->where(['=', 'type', 1])->orderBy('name')
                ->asArray()->all(),
            'name',
            'name'
        );
    }

    /**
     * {@inheritdoc}
     * @return user_name
     */
    public static function getName($id)
    {
        $username = self::find()->select(['username'])
            ->where(['=', 'id', $id])->one();
        return $username->username;
    }

    /**
     * {@inheritdoc}
     * @return mixed username array
     */
    public static function getUsernames($ids)
    {
        return ArrayHelper::map(
            self::find()
                ->select(['id', 'username'])
                ->orderBy('username')
                ->where(['IN', 'id', $ids])
                ->asArray()
                ->all(),
            'id',
            'username'
        );
    }

    /**
     * @return \yii\db\ActiveQuery
     * @return mixed User Names
     */
    public function getUsers()
    {
        return $this->hasOne(self::className(), ['id' => 'created_by']);
    }

    /**
     * {@inheritdoc}
     * @return UserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserQuery(get_called_class());
    }

    /**
     * {@inheritdoc}
     */
    public function getDefaultPassword()
    {
        static::DEFAULT_PASSWORD;
    }

    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

    public static function findByPasswordResetToken($token)
    {
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        if ($timestamp + $expire < time()) {
            // token expired
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        //return $this->password === sha1($password);
        //return Yii::$app->security->validatePassword($password, $this->password);
        return Yii::$app->getSecurity()->validatePassword(
            $password,
            $this->password
        );
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        //$this->password = Security::generatePasswordHash($password);
        //$this->password = Yii::$app->security->generatePasswordHash($password);
        $this->password = Yii::$app->getSecurity()->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() .
            '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function behaviors()
    {
        return [
            [
                'class' => UserDbLogBehavior::className()
            ],
        ];
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\Region;
use app\models\District;
use app\models\UserSearch;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Controller;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'create', 'index', 'view'],
                'rules' => [
                    [
                        'actions' => [
                            'logout', 'create', 'index', 'view', 'profile'
                        ],
                        'allow' => true,
                        // 'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($insert)
    {
        if (Yii::$app->user->isGuest) {
            return false;
        } else {
            return true;
        }
    }

    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render(
            'index',
            [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]
        );
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render(
            'view',
            [
                'model' => $this->findModel($id),
            ]
        );
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionProfile()
    {
        return $this->render(
            'profile',
            [
                'model' => $this->findModel(Yii::$app->user->id),
            ]
        );
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        // $this->layout = "main-plain";
        $model = new User();
        if ($model->load(Yii::$app->request->post()) && $model->save(false)) {
            Yii::$app->session->setFlash(
                'success',
                'Success! New user (' . $model->username . ') successfully created!'
            );
            return $this->redirect(['index']);
        }
        return $this->render(
            'create',
            [
                'model' => $model,
            ]
        );
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save(false)) {
            Yii::$app->session->setFlash(
                'success',
                'Success. Update action completed successfully.!'
            );
            return $this->redirect(['index']);
        }

        return $this->render(
            'update',
            [
                'model' => $model,
            ]
        );
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->setFlash(
            'success',
            'Success. Delete action completed successfully.!'
        );

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionDeleteAll()
    {
        $pk = Yii::$app->request->post('pk');
        $explode = explode(',', $pk);
        if ($explode) {
            foreach ($explode as $v) {
                if ($v) {
                    $this->findModel($v)->delete();
                }
            }
        }
        echo 1;
    }

    /**
     * Lists all Regions based on Filter Zones.
     * @return mixed
     */
    public function actionRegion()
    {
        Yii::$app->response->format = Yii\web\Response::FORMAT_JSON;
        if (isset($_POST['depdrop_parents'])) {
            $zones = $_POST['depdrop_parents'];
            if ($zones != null) {
                $zone = $zones[0];
                return self::getRegion($zone);
            }
        }
        return ['output' => '', 'selected' => ''];
    }

    /**
     * Lists all Districts based on Filter Regions.
     * @return mixed
     */
    public function actionDistrict()
    {
        Yii::$app->response->format = Yii\web\Response::FORMAT_JSON;
        if (isset($_POST['depdrop_parents'])) {
            $regions = $_POST['depdrop_parents'];
            if ($regions != null) {
                $region = $regions[0];
                return self::getDistrict($region);
            }
        }
        return ['output' => '', 'selected' => ''];
    }

    private function getRegion($zone)
    {
        $out = Region::find()
            ->select(['id', 'name'])
            ->where(['zone_id' => $zone])
            ->all();
        return ['output' => $out, 'selected' => ''];
    }
    private function getDistrict($region)
    {
        $out = District::find()
            ->select(['id', 'name'])
            ->where(['region_id' => $region])
            ->all();
        return ['output' => $out, 'selected' => ''];
    }

    /**
     * Fetch DropDown Data List for a child/DepDrop.
     *
     * @return mixed DepDrop Data List and Selected Value
     */
    public function actionDepdrop()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = [];
        $dataList = [];
        $selected = '';
        if (!empty($_POST['depdrop_params'])) {
            $selected = $_POST['depdrop_params'][0];
            // $selected = end($_POST['depdrop_params']);
        }
        if (isset($_POST['depdrop_parents'])) {
            $value = end($_POST['depdrop_parents']);
            $key = array_key_last($_POST['depdrop_parents']);
            // $out = $value;
            // $out = $key;
            // die(print_r($value));
            if ($key == 0) {
                $dataList = Region::find()
                    ->select(['id', 'name'])
                    ->where(['zone_id' => $value])
                    ->all();
            } elseif ($key == 1) {
                $dataList = District::find()
                    ->select(['id', 'name'])
                    ->where(['region_id' => $value])
                    ->all();
            }

            if ($value != null && count($dataList) > 0) {
                // return ['output' => $out, 'selected' => ''];
                return ['output' => $out, 'selected' => $selected];
            }
        }
        return ['output' => '', 'selected' => ''];
    }
}

views/user/_form.php
<?php

use app\models\Zone;
use yii\helpers\Url;
use yii\helpers\Html;
use app\models\LocArea;
use app\models\AuthItem;
use kartik\select2\Select2;
use kartik\depdrop\DepDrop;
use yii\helpers\ArrayHelper;
use kartik\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="user-form">
    <?php
    if (empty($model) || $model->isNewRecord) {
        $model->role = null;
        $fname = $lname = $role = '';
        $regionId = $districtId = null;
        $regionData = $districtData = [];
    } else {
        $role = $model->roles->item_name;
        $fname = explode('.', $model->username)[0];
        $lname = explode('.', $model->username)[1];
        $district = empty($model->district_id) ?
            [] : LocArea::getDistrict($model->district_id);
        $region = empty($model->region_id) ?
            [] : LocArea::getRegion($model->region_id);

        $districtId = !empty($district) ? $district->id : null; //32
        $regionId = !empty($region) ? $region->id : null; //7
        $districtData = empty($district) ? [] : [
            $district->id => $district->name,
        ];
        $regionData = empty($district) ? [] : [
            $region->id => $region->name,
        ];
    }
    $url = Url::to(['/user/depdrop']);
    $regionUrl = Url::to(['/user/region']);
    $districtUrl = Url::to(['/user/district']);
    $form = ActiveForm::begin(
        [
            'type' => ActiveForm::TYPE_HORIZONTAL,
            'options' => ['enctype' => 'multipart/form-data']
        ]
    ); ?>
    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'first_name')
                ->textInput(
                    [
                        'id' => 'fname',
                        'value' => $fname,
                        'maxlength' => true,
                        'style' => 'text-transform:capitalize'
                    ]
                ) ?>
            <?= $form->field($model, 'last_name')
                ->textInput(
                    [
                        'id' => 'lname',
                        'value' => $lname,
                        'maxlength' => true,
                        'style' => 'text-transform:capitalize'
                    ]
                ) ?>
            <?= $form->field($model, 'username')
                ->textInput(
                    [
                        'maxlength' => true, 'readOnly' => false, 'id' => 'username'
                    ]
                ) ?>
            <?= $form->field($model, 'designation')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'zone_id')->widget(
                Select2::classname(),
                [
                    'data' => ArrayHelper::map(
                        Zone::find()->select(['id', 'name'])->all(),
                        'id',
                        'name'
                    ),
                    'theme' => Select2::THEME_KRAJEE,
                    'size' => Select2::MEDIUM,
                    'language' => 'en',
                    'options' => [
                        'id' => 'zone',
                        'placeholder' => 'Select Zone..',
                        'class' => 'form-control'
                    ],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]
            ); ?>
            <?= $form->field($model, 'region_id')->widget(
                DepDrop::classname(),
                [
                    'data' => $regionData,
                    'type' => DepDrop::TYPE_SELECT2,
                    'options' => ['id' => 'region'],
                    'pluginOptions' => [
                        'url' => $regionUrl,
                        'depends' => ['zone'],
                        'loadingText' => 'Loading Regions..',
                    ],
                    'select2Options' => [
                        'pluginOptions' => [
                            'width' => '100%',
                            'size' => Select2::MEDIUM,
                        ]
                    ],
                ]
            ); ?>
            <?= $form->field($model, 'district_id')->widget(
                DepDrop::classname(),
                [
                    'data' => $districtData,
                    'type' => DepDrop::TYPE_SELECT2,
                    'options' => ['id' => 'district'],
                    'pluginOptions' => [
                        'initialize' => true,
                        'url' => $districtUrl,
                        'depends' => ['region'],
                        'initDepends' => ['zone'],
                        'loadingText' => 'Loading Districts..'
                    ],
                    'select2Options' => [
                        'pluginOptions' => [
                            'width' => '100%',
                            'size' => Select2::MEDIUM,
                        ]
                    ]
                ]
            ); ?>
        </div>
        <div class="col-md-12">
            <?= $form->field($model, 'coyno')
                ->textInput(['maxlength' => true, 'style' => 'text-transform:capitalize']) ?>
            <?=
                $form->field($model, 'role')->widget(
                    Select2::classname(),
                    [
                        'data' => ArrayHelper::map(
                            AuthItem::find()->select(['name', 'name'])
                                ->where(['type' => 1])->all(),
                            'name',
                            'name'
                        ),
                        'theme' => Select2::THEME_KRAJEE,
                        'size' => Select2::MEDIUM,
                        'language' => 'en',
                        'options' => [
                            'id' => 'role',
                            'class' => 'form-control',
                            'placeholder' => 'Select User Role..',
                        ],
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                    ]
                );
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <?= Html::submitButton(
                $model->isNewRecord ? Yii::t('app', 'Create') :
                    Yii::t('app', 'Update'),
                [
                    'class' => $model->isNewRecord ?
                        'btn btn-success' : 'btn btn-primary'
                ]
            ) ?>
            <?= Html::resetButton(
                Yii::t('app', 'Reset'),
                [
                    'id' => 'resetButton',
                    'class' => 'btn btn-default'
                ]
            ) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

<?php $script = <<< JS
// JS Code
    var timerid = 0;
    $(function(e) {
        $('#role').val('$role').trigger('change');
        $("#username").prop("readonly", true);
        $("#fname").on("input", function(e) {
            var fName = $(this).val().toLowerCase();
            var lName = $("#lname").val().toLowerCase();
            if ($(this).data("lastval") != fName) {
                $(this).data("lastval", fName);
                clearTimeout(timerid);
                timerid = setTimeout(function(e) {
                    //Change action
                    if(fName && !lName){
                        $("#username").css("color","red").val(fName);
                    }else if(!fName && lName){
                        $("#username").css("color","red").val(lName);
                    }else{
                        $("#username").css("color","green").val(fName + "." + lName);
                    }
                }, 500);
                $("#lname").prop("readonly", false);
            };
        });
        $("#lname").on("input", function(e) {
            var fName = $("#fname").val().toLowerCase();
            var lName = $(this).val().toLowerCase();
            if ($(this).data("lastval") != lName) {

                $(this).data("lastval", lName);
                clearTimeout(timerid);

                timerid = setTimeout(function(e) {
                    //Change action
                    if(fName && !lName){
                        $("#username").css("color","red").val(fName);
                    }else if(!fName && lName){
                        $("#username").css("color","red").val(lName);
                    }else{
                        $("#username").css("color","green").val(fName + "." + lName);
                    }
                }, 500);
            };
        });
        $("#resetButton").on("click", function(e) {
            $("#zone").val(null).trigger('change');
            $("#region").val(null).trigger('change');
            $("#district").val(null).trigger('change');
        });
    });
JS;
$this->registerJs($script);
?>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'full_name') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'designation')?>

    <?php // echo $form->field($model, 'coyno')?>

    <?php // echo $form->field($model, 'auth_key')?>

    <?php // echo $form->field($model, 'password_reset_token')?>

    <?php // echo $form->field($model, 'access_token')?>

    <?php // echo $form->field($model, 'status')?>

    <?php // echo $form->field($model, 'created_at')?>

    <?php // echo $form->field($model, 'updated_at')?>

    <?php // echo $form->field($model, 'create_by')?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => 'User',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <div class="page-header">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/index.php
<?php

use app\models\User;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Users');
$this->params['breadcrumbs'][] = $this->title;
$date = date('Y-m-dTH:i:s');
$id = 'user';
?>
<div class="user-index">
    <?php
    $cols = [
        'username',
        [
            'class' => 'kartik\grid\DataColumn',
            'attribute' => 'email',
            'format' => 'email',
            'visible' => false,
        ],
        'designation',
        'coyno',
        [
            'class' => 'kartik\grid\DataColumn',
            'attribute' => 'role',
            'filter' => User::getRoleItems(),
            'filterType' => GridView::FILTER_SELECT2,
            'filterWidgetOptions' => [
                'options' => ['prompt' => 'Select Role'],
                'pluginOptions' => [
                    'allowClear' => true,
                    'width' => ''
                ],
            ],
            'format' => 'raw',
            'value' => 'roles.item_name',
        ],
        // 'auth_key',
        [
            'class' => 'kartik\grid\BooleanColumn',
            'attribute' => 'status',
            'vAlign' => 'middle',
        ],
        [
            'class' => 'kartik\grid\DataColumn',
            'attribute' => 'created_at',
            'format' => 'datetime',
            'filterType' => GridView::FILTER_DATE,
            'filterWidgetOptions' => [
                'pluginOptions' => ['format' => 'yyyy-mm-dd']
            ],
        ],
        [
            'class' => 'kartik\grid\DataColumn',
            'attribute' => 'updated_at',
            'format' => 'datetime',
            'filterType' => GridView::FILTER_DATE,
            'filterWidgetOptions' => [
                'pluginOptions' => ['format' => 'yyyy-mm-dd']
            ],
        ],
        [
            'class' => 'kartik\grid\DataColumn',
            'attribute' => 'created_by',
            'filter' => User::getUsernames(User::find()->select(['created_by'])),
            'filterType' => GridView::FILTER_SELECT2,
            'filterWidgetOptions' => [
                'options' => ['prompt' => 'Select Creator'],
                'pluginOptions' => [
                    'allowClear' => true,
                    'width' => ''
                ],
            ],
            'format' => 'raw',
            'value' => 'users.username'
        ]
    ];
    echo $this->render(
        '../common/actions.php',
        [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'title' => $this->title,
            'date' => $date,
            'cols' => $cols,
            'id' => $id
        ]
    );
    ?>
</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'User',
]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="user-update">
    <div class="page-header">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>
    <?=
        $this->render('_form', [
            'model' => $model,
        ])
    ?>
</div>